global: convert indentation-TABs to spaces
Transformed via this shell code:
t=$'\t'
git ls-files \
  | grep -vE '(^|/)((GNU)?[Mm]akefile|ChangeLog)|\.(am|mk)$' \
  | grep -vE 'tests/pr/|help2man' \
  | xargs grep -lE "^ *$t" \
  | xargs perl -MText::Tabs -ni -le \
    '$m=/^( *\t[ \t]*)(.*)/; print $m ? expand($1) . $2 : $_'

diff --git a/zdiff.in b/zdiff.in
--- a/zdiff.in
+++ b/zdiff.in
@@ -26,7 +26,7 @@ PATH=$bindir:$PATH
 
 case $1 in
   --__cmp) shift
-	prog=cmp;  cmp='${CMP-cmp}'  ;;
+        prog=cmp;  cmp='${CMP-cmp}'  ;;
   *)    prog=diff; cmp='${DIFF-diff}';;
 esac
 
@@ -88,78 +88,78 @@ if test $# -eq 1; then
     exit 2;;
   esac
 elif test $# -eq 2; then
-	case "$1" in
-	*[-.]gz* | *[-.][zZ] | *.t[ga]z | -)
+        case "$1" in
+        *[-.]gz* | *[-.][zZ] | *.t[ga]z | -)
                 case "$2" in
-		*[-.]gz* | *[-.][zZ] | *.t[ga]z | -)
-		    if test "$1$2" = --; then
-			gzip_status=$(
-			  exec 4>&1
-			  (gzip -cdfq - 4>&-; echo $? >&4) 3>&- |
-			    eval "$cmp" - - >&3
-			)
-		    elif
-			# Reject Solaris 8's buggy /bin/bash 2.03.
-			echo X |
-			 (echo X | eval "$cmp" /dev/fd/5 - >/dev/null 2>&1) \
-				5<&0
-		    then
-			gzip_status=$(
-			  exec 4>&1
-			  (gzip -cdfq -- "$1" 4>&-; echo $? >&4) 3>&- |
-			    ( (gzip -cdfq -- "$2" 4>&-; echo $? >&4) 3>&- 5<&- </dev/null |
-			       eval "$cmp" /dev/fd/5 - >&3) 5<&0
-			)
-			cmp_status=$?
-			case $gzip_status in
-			  *[1-9]*) gzip_status=1;;
-			  *) gzip_status=0;;
-			esac
-			(exit $cmp_status)
-		    else
-			F=`expr "/$2" : '.*/\(.*\)[-.][zZtga]*$'` || F=$prog
-			tmp=
-			trap '
-			  test -n "$tmp" && rm -f "$tmp"
-			  (exit 2); exit 2
-			' HUP INT PIPE TERM 0
-			if type mktemp >/dev/null 2>&1; then
-			  tmp=`mktemp -t -- "$F.XXXXXX"` || exit 2
-			else
-			  set -C
-			  tmp=${TMPDIR-/tmp}/$F.$$
-			fi
-			gzip -cdfq -- "$2" > "$tmp" || exit 2
-			gzip_status=$(
-			  exec 4>&1
-			  (gzip -cdfq -- "$1" 4>&-; echo $? >&4) 3>&- |
-			    eval "$cmp" - '"$tmp"' >&3
-			)
+                *[-.]gz* | *[-.][zZ] | *.t[ga]z | -)
+                    if test "$1$2" = --; then
+                        gzip_status=$(
+                          exec 4>&1
+                          (gzip -cdfq - 4>&-; echo $? >&4) 3>&- |
+                            eval "$cmp" - - >&3
+                        )
+                    elif
+                        # Reject Solaris 8's buggy /bin/bash 2.03.
+                        echo X |
+                         (echo X | eval "$cmp" /dev/fd/5 - >/dev/null 2>&1) \
+                                5<&0
+                    then
+                        gzip_status=$(
+                          exec 4>&1
+                          (gzip -cdfq -- "$1" 4>&-; echo $? >&4) 3>&- |
+                            ( (gzip -cdfq -- "$2" 4>&-; echo $? >&4) 3>&- 5<&- </dev/null |
+                               eval "$cmp" /dev/fd/5 - >&3) 5<&0
+                        )
                         cmp_status=$?
-			rm -f "$tmp" || gzip_status=$?
-			trap - HUP INT PIPE TERM 0
-			(exit $cmp_status)
-		    fi;;
-		*)
-		    gzip_status=$(
-		      exec 4>&1
-		      (gzip -cdfq -- "$1" 4>&-; echo $? >&4) 3>&- |
-		        eval "$cmp" - '"$2"' >&3
-		    );;
+                        case $gzip_status in
+                          *[1-9]*) gzip_status=1;;
+                          *) gzip_status=0;;
+                        esac
+                        (exit $cmp_status)
+                    else
+                        F=`expr "/$2" : '.*/\(.*\)[-.][zZtga]*$'` || F=$prog
+                        tmp=
+                        trap '
+                          test -n "$tmp" && rm -f "$tmp"
+                          (exit 2); exit 2
+                        ' HUP INT PIPE TERM 0
+                        if type mktemp >/dev/null 2>&1; then
+                          tmp=`mktemp -t -- "$F.XXXXXX"` || exit 2
+                        else
+                          set -C
+                          tmp=${TMPDIR-/tmp}/$F.$$
+                        fi
+                        gzip -cdfq -- "$2" > "$tmp" || exit 2
+                        gzip_status=$(
+                          exec 4>&1
+                          (gzip -cdfq -- "$1" 4>&-; echo $? >&4) 3>&- |
+                            eval "$cmp" - '"$tmp"' >&3
+                        )
+                        cmp_status=$?
+                        rm -f "$tmp" || gzip_status=$?
+                        trap - HUP INT PIPE TERM 0
+                        (exit $cmp_status)
+                    fi;;
+                *)
+                    gzip_status=$(
+                      exec 4>&1
+                      (gzip -cdfq -- "$1" 4>&-; echo $? >&4) 3>&- |
+                        eval "$cmp" - '"$2"' >&3
+                    );;
                 esac;;
         *)      case "$2" in
-		*[-.]gz* | *[-.][zZ] | *.t[ga]z | -)
-			gzip_status=$(
-			  exec 4>&1
-			  (gzip -cdfq -- "$2" 4>&-; echo $? >&4) 3>&- |
-			    eval "$cmp" '"$1"' - >&3
-			);;
-		*)	eval "$cmp" '"$1"' '"$2"';;
+                *[-.]gz* | *[-.][zZ] | *.t[ga]z | -)
+                        gzip_status=$(
+                          exec 4>&1
+                          (gzip -cdfq -- "$2" 4>&-; echo $? >&4) 3>&- |
+                            eval "$cmp" '"$1"' - >&3
+                        );;
+                *)	eval "$cmp" '"$1"' '"$2"';;
                 esac;;
-	esac
+        esac
 else
-	echo >&2 "$0: invalid number of operands; try \`$0 --help' for help"
-	exit 2
+        echo >&2 "$0: invalid number of operands; try \`$0 --help' for help"
+        exit 2
 fi
 
 cmp_status=$?
diff --git a/zmore.in b/zmore.in
--- a/zmore.in
+++ b/zmore.in
@@ -57,36 +57,36 @@ fi
 
 if test $# = 0; then
     if test -t 0; then
-	echo >&2 "$0: invalid number of operands; try \`$0 --help' for help"
+        echo >&2 "$0: invalid number of operands; try \`$0 --help' for help"
     else
-	gzip -cdfq | eval ${PAGER-more}
+        gzip -cdfq | eval ${PAGER-more}
     fi
 else
     FIRST=1
     for FILE
     do
-	case $FILE in
-	--h*) exec echo "$usage";;
-	--v*) exec echo "$version";;
-	esac
+        case $FILE in
+        --h*) exec echo "$usage";;
+        --v*) exec echo "$version";;
+        esac
 
-	< "$FILE" || continue
-	if test $FIRST -eq 0; then
-		echo $n1 "--More--(Next file: $FILE)$n2"
-		stty $cb -echo 2>/dev/null
-		ANS=`dd bs=1 count=1 2>/dev/null`
-		stty $ncb echo 2>/dev/null
-		echo " "
-		case "$ANS" in
-		[eq]) exit;;
-		esac
-	fi
-	if test "$ANS" != 's'; then
-		echo "------> $FILE <------"
-		gzip -cdfq -- "$FILE" | eval ${PAGER-more}
-	fi
-	if test -t 1; then
-		FIRST=0
-	fi
+        < "$FILE" || continue
+        if test $FIRST -eq 0; then
+                echo $n1 "--More--(Next file: $FILE)$n2"
+                stty $cb -echo 2>/dev/null
+                ANS=`dd bs=1 count=1 2>/dev/null`
+                stty $ncb echo 2>/dev/null
+                echo " "
+                case "$ANS" in
+                [eq]) exit;;
+                esac
+        fi
+        if test "$ANS" != 's'; then
+                echo "------> $FILE <------"
+                gzip -cdfq -- "$FILE" | eval ${PAGER-more}
+        fi
+        if test -t 1; then
+                FIRST=0
+        fi
     done
 fi
