wrapper scripts: write diagnostics to stderr, not to stdout
* zforce.in: In case of usage error, output short error diagnostics to
stderr instead of printing help text to stdout.
* zmore.in: Likewise.
* znew.in: Likewise.

diff --git a/zforce.in b/zforce.in
--- a/zforce.in
+++ b/zforce.in
@@ -44,7 +44,7 @@ not compress them twice.
 Report bugs to <bug-gzip@gnu.org>."
 
 if test $# = 0; then
-  echo "$usage"
+  echo >&2 "$0: invalid number of operands; try \`$0 --help' for help"
   exit 1
 fi
 
diff --git a/zmore.in b/zmore.in
--- a/zmore.in
+++ b/zmore.in
@@ -57,7 +57,7 @@ fi
 
 if test $# = 0; then
     if test -t 0; then
-	echo "$usage"
+	echo >&2 "$0: invalid number of operands; try \`$0 --help' for help"
     else
 	gzip -cdfq | eval ${PAGER-more}
     fi
diff --git a/znew.in b/znew.in
--- a/znew.in
+++ b/znew.in
@@ -97,7 +97,7 @@ do
 done
 
 if test $# -eq 0; then
-  echo "$usage"
+  echo >&2 "$0: invalid number of operands; try \`$0 --help' for help"
   exit 1
 fi
 
